export 'package:manage_student_credits_mobile/widgets/background.dart';
export 'package:manage_student_credits_mobile/widgets/card_container.dart';
export 'package:manage_student_credits_mobile/widgets/screen_container.dart';
export 'package:manage_student_credits_mobile/widgets/student_card.dart';
export 'package:manage_student_credits_mobile/widgets/student_detail_card.dart';
export 'package:manage_student_credits_mobile/widgets/subject_card.dart';
export 'package:manage_student_credits_mobile/widgets/teacher_card.dart';
export 'package:manage_student_credits_mobile/widgets/teacher_detail_card.dart';
export 'package:manage_student_credits_mobile/widgets/text_detail.dart';
